### ISSUE TITLE
issue with absolute path

### ISSUE THREAD

**Issue by wassimsalib** [dommmel/fill-pdf#12]
I had an issue when passing an absolute path to the `generatePdf` function. My path looked something like this `/srv/www/api/services/../../assets/template.pdf` because this path is generated dynamically using `__dirname` , I temp. fixed this issue by removing `__dirname` from the `generatePdf` in https://github.com/dommmel/fill-pdf/blob/master/index.js#L60 , but I didn't raise a pull request because I didn't test it thoroughly.

HINT: I can't use relative paths, because `fill-pdf` module is installed locally in a different folder than where it is installed on my production env. but my api code / folder structure is the same, that's why am forming the path to the .pdf template from the service.

**Comment by ScottONeal** [comment]
Thank you for reporting the issue and using fill-pdf!

I just committed a fix that should resolve your issue. Please run `npm install` again and see if everything works.

Added a simple test that tests absolute paths. See:

https://github.com/dommmel/fill-pdf/blob/master/test/test.js#L66

**Comment by wassimsalib** [comment]
Wow, that was fast, thanks a lot for the quick response :+1: , I have tested it and it is working now. Thanks again.

**Comment by wassimsalib** [comment]
I was testing the module with node 0.10.40 and I got an error ` path.isAbsolute(templatePath) ? templatePath : path.joi
                            ^
TypeError: Object #<Object> has no method 'isAbsolute'` so is there a different `isAbsolute` function than the one in `path` to be compatible with older versions of node?
