### ISSUE TITLE
Exception when filling a PDF

### ISSUE THREAD

**Issue by wassimsalib** [dommmel/fill-pdf#16]
I was trying to fill a PDF form and I have got this exception, but I couldn't figure out what is happening. I tried to open the PDF form and manually fill it with the same data and I didn't notice any issue, except I found it is formatting my inputs (i.e if I type 9999999999 in phone number, it replaces it with (999) 999-9999)

```
stderr: Unhandled Java Exception:
java.lang.ClassCastException: com.lowagie.text.pdf.PRIndirectReference cannot be cast to com.lowagie.text.pdf.PdfNumber
   at com.lowagie.text.pdf.PdfReader.getNormalizedRectangle(pdftk)
   at com.lowagie.text.pdf.AcroFields.getAppearance(pdftk)
   at com.lowagie.text.pdf.AcroFields.setField(pdftk)
   at com.lowagie.text.pdf.AcroFields.setFields(pdftk)

debug: Generating - Error:
 Error: Non 0 exit code from pdftk spawn: 2
    at ChildProcess.<anonymous> (/var/tmp/sharpone/node_modules/fill-pdf/index.js:68:16)
    at ChildProcess.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:820:12) [Error: Non 0 exit code from pdftk spawn: 2]

```

**Comment by ScottONeal** [comment]
Hey @wassimsalib, is this still an issue or have you moved on? I've got sometime to help if it still an issue.

Looks like it's an issue w/ the PDFs input formatting and trying to fill it.

**Comment by wassimsalib** [comment]
Hey @ScottONeal , Thanks for getting back to me, yes unfortunately I still have the issue, and I suspected my PDF format, but couldn't figure out what is happening, so your tips will be much appreciated :+1:

**Comment by ScottONeal** [comment]
Okay, can you give me an example of how you are using the module and loading data into your PDF?

**Comment by wassimsalib** [comment]
This is how my code exactly looks
```
var formData={
"fieldName": "fieldValue" //Sometimes the value is a number
};
console.log("checking if PDF exists: ", fs.existsSync(__dirname + '/../../assets/templates/myPDF.pdf'));
 fillPdf.generatePdf(formData, __dirname + '/../../assets/templates/myPDF.pdf', function (err, pdf) {
if(err)
return callback(err);
return callback(null, pdf);
});
```

**Comment by ScottONeal** [comment]
Does the error only throw when you try to put a `String` into the number formatted PDF field, or does it happen with `Numbers` too?

**Comment by wassimsalib** [comment]
The last time I tested it was few days ago, but what I remember is that I even tried to fill only one basic string field instead of sending the whole form data, and it was still giving the error.

**Comment by ScottONeal** [comment]
Okay. I'm curious as to the formatting of your PDF form inputs. If you have a phone number field and you are trying to put a string of non numerics, is that what is throwing the error?

```js
var formData = {
  phoneNumber: 'ab12345' // this should be all numbers
}
```

Have you tried ensure proper validity of values you are inserting into the pdf?

```js
formData.phoneNumber = formData.phoneNumber.match(/\d+/)[0]
// -> '12345'
```

**Comment by ScottONeal** [comment]
closing inactive
