### ISSUE TITLE
process hangs

### ISSUE THREAD

**Issue by kyledunaway** [dommmel/fill-pdf#30]
`pdftk /Users/Desktop/medical/node_modules/fill-pdf/test.pdf fill_form - output /var/folders/bg/z3yjjyjj1g3d3w3sxdvsjyy80000gn/T/11686-1158-1knf4m9.pdf`

process just hangs, am I missing something?

**Comment by ScottONeal** [comment]
Is this still an issue?

**Comment by ves-krd** [comment]
@ScottONeal I believe it is.  I could have been doing something wrong.  I moved to a different module.

**Comment by aszs** [comment]
I had the same problem until I fixed by installing the correct version of pdftk, see:
https://stackoverflow.com/questions/39750883/pdftk-hanging-on-macos-sierra
