### ISSUE TITLE
Escape parenthesis

### ISSUE THREAD

**Issue by fedyunin** [dommmel/fill-pdf#31]
Hello! I faced with issue that parenthesis not escaped by your module.

I not sure is it issue or not. Probably I need escape them from my side, before pass field values to your module. 

What do you think about it?
Is it make sense escape parenthesis in the line 22, e.g: 

`var value = data[name].toString().replace('\r\n','\r').replace(/(?=[()])/g, '\\');
`

Thanks!

**Comment by ScottONeal** [comment]
If you could submit a PR with this change and a couple of unit tests I can merge!

**Comment by j-halbert** [comment]
I'm submitting a PR w/ unit tests.  

I ran into this problem myself, parens in the input can cause fdf data to appear in the form (e.g. we see >><<\T (FieldName) instead of those fields being filled properly)
