### ISSUE TITLE
Not working with special characters like åäö

### ISSUE THREAD

**Issue by hogenf** [dommmel/fill-pdf#32]
Cant get it to work properly with special characters lite åäö. Works fine with normal latin characters. 

After some digging I think the problem is with pdftk and how it handles fonts, but im not certain.

php-pdftk is solving it with need_appearances I think.
https://github.com/mikehaertl/php-pdftk

Have tested with /test/resources/test.pdf
pdftk 2.02
fill-pdf 0.5.0

**Comment by hogenf** [comment]
I have it working in shell now with the need_appearances option and without flatten. 

`pdftk test.pdf fill_form test.fdf output form.filled.pdf need_appearances`

Im new too nodejs so I do not know where in your code I should add need_appearances or/and remove flatten?

[test_fdf_pdf.zip](https://github.com/dommmel/fill-pdf/files/560407/test_fdf_pdf.zip)

**Comment by ScottONeal** [comment]
Here is the line you would want to change: https://github.com/dommmel/fill-pdf/blob/master/index.js#L42

I think the best option would be to submit a PR in which the user can extend the arguments send to `pdftk`

**Comment by Mousaka** [comment]
I'm still having this issue with "fill-pdf": "^1.1.0" =(
