### ISSUE TITLE
getting error on method `generatePdf` whilst using azure app service

### ISSUE THREAD

**Issue by shah-smit** [dommmel/fill-pdf#34]
It throws this error: `{
  "code": "EPIPE",
  "errno": "EPIPE",
  "syscall": "write"
}`

**Comment by cranesandcaff** [comment]
@ScottONeal I found this while looking to see if Azure App Service supports PDF TK, you closed it, do you know if it does?

**Comment by ScottONeal** [comment]
I closed the issue because it was stale, I do not know if it runs on Azure. If you are able to test compatibility I can work with you to fix any issues

**Comment by cranesandcaff** [comment]
Thanks for reminding me to update this! If you use Azure Linux App Service you can add `apk add pdftk` to your start script in package.json and your container will install it on start!
