### ISSUE TITLE
Could you document then options that can be passed to pdftk?

### ISSUE THREAD

**Issue by sfabriece** [dommmel/fill-pdf#37]
Hi, thanks for the module.

It took me a while to figure out how to flatten the generated pdf.

it would be nice to have an example that involves passing args to pdftk and optionally available options and what they do.

😃

**Comment by ScottONeal** [comment]
Hey, I'm not actively working on this project. But, I will accept PRs!

**Comment by jpetitcolas** [comment]
New documentation proposed in https://github.com/dommmel/fill-pdf/pull/44, for the exact same use case. :)
