### ISSUE TITLE
Support custom directories for template files

### ISSUE THREAD

**Issue by peny** [dommmel/fill-pdf#4]
Right now the directory where template files are supposed to be located is hardcoded to the ```./app``` directory of the project root.

https://github.com/dommmel/fill-pdf/blob/master/index.js#L58

I think it would be wise to be able to specify where the templates are located yourself, using ```__dirname``` etc. might be a bit bothersome but it makes for a much more flexible project.

However, this would be a *breaking change* so I would really like input from @dommmel before I start working on a pull request.

**Comment by dommmel** [comment]
@peny sure, go ahead! 
I haven't used this since I wrote it for a client a while ago. Would love to see this becoming useful for more people (like you).

Looking forward to your pull request(s).

**Comment by ScottONeal** [comment]
The latest commit has been updated to use `__dirname` as the base for looking for pdf files. However, in the future, I believe we should allow an option for a base directory to be used.

https://github.com/dommmel/fill-pdf/blob/master/index.js#L60

Closing ticket

**Comment by peny** [comment]
Oh what joy! :+1:
