### ISSUE TITLE
Add Release Notes/Changelog

### ISSUE THREAD

**Issue by westy92** [dommmel/fill-pdf#41]
Could you please add release notes detailing what breaking changes came with version 1.0.0?

I've seen people add a `CHANGELOG.md` and/or add release notes [here](https://github.com/dommmel/fill-pdf/releases).

**Comment by westy92** [comment]
@dommmel any update on this?

**Comment by westy92** [comment]
@dommmel any update on this?

**Comment by westy92** [comment]
Taking a quick look at the code:

# 1.1.0
* Bugfix to preserve form data encoding and escape form field names. #42

# 1.0.0
* Bugfix to escape parenthesis in form data. #40

**Comment by ScottONeal** [comment]
Even though it has been a really long time since any action has been performed on this repo, I will look into doing this. Thanks!

**Comment by westy92** [comment]
Great! Thank you.

**Comment by ScottONeal** [comment]
Just curious, are you still actively using this library? It may be time to 2.0.0 and add some quality of life features/fixes.

**Comment by westy92** [comment]
I'm not, but it looks like 1300 people a week are downloading it!
https://www.npmjs.com/package/fill-pdf

**Comment by westy92** [comment]
FYI a typical best-practice is to keep issues open until they are resolved.
Thanks for this library! It was helpful in the past and I was happy to contribute.
