### ISSUE TITLE
Checkboxes

### ISSUE THREAD

**Issue by chriskvik** [dommmel/fill-pdf#7]
Is it possible to mark checkboxes with the package in it's current version?

**Comment by dommmel** [comment]
Sorry for taking so long to reply. I've never tried using checkboxes ;)

**Comment by ScottONeal** [comment]
Yes you can use checkboxes. Typically, your checkbox fieldname needs to have a value of `'Yes'` for the mark to show up. This is being done in one of the tests see:

https://github.com/dommmel/fill-pdf/blob/master/test/test.js#L50
